apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.backend.labelName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.selector }}
    spec:
      containers:
      - name: {{ .Values.backend.containerName }}
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
          name: {{ .Values.backend.portName }}
        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory | quote }}
            cpu: {{ .Values.backend.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory | quote }}
            cpu: {{ .Values.backend.resources.limits.cpu | quote }}
        envFrom:
        - secretRef:
            name: {{ .Values.backend.secretName }} 