{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "{{ .Values.ingress.cloudflareProxied }}"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.cloudflareTarget }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /todo/
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.serviceName }}
            port:
              name: {{ .Values.frontend.servicePortName }}
      - path: /todo/api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.serviceName }}
            port:
              name: {{ .Values.backend.servicePortName }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.jenkins.serviceName }}
            port:
              number: {{ .Values.jenkins.port }}
{{- end }} 