apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.secret.MYSQL_HOST }}
  MYSQL_PORT: {{ .Values.secret.MYSQL_PORT | quote }}
  MYSQL_USER: {{ .Values.secret.MYSQL_USER }}
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD }}
  MYSQL_DATABASE: {{ .Values.secret.MYSQL_DATABASE }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD }} 